# Generated by Django 3.2 on 2022-04-28 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitem',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.author'),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='classification_type',
            field=models.CharField(blank=True, choices=[('a', 'Anime'), ('s', 'Series'), ('m', 'Movie'), ('o', 'OVA')], default='s', max_length=1, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Capa'),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='new_season_in',
            field=models.DateField(blank=True, null=True, verbose_name='Data Nova Temporada'),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='new_season_preview',
            field=models.BooleanField(blank=True, verbose_name='Prevista Nova Temporada'),
        ),
    ]
