# Generated by Django 3.2 on 2022-04-28 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20220427_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogitem',
            options={'verbose_name': 'Iten Catalogo', 'verbose_name_plural': 'Itens Catalogos'},
        ),
        migrations.RenameField(
            model_name='catalog',
            old_name='Title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='author',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='author',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Alterado em'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Alterado em'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Alterado em'),
        ),
        migrations.AddField(
            model_name='genre',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='genre',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Alterado em'),
        ),
        migrations.AddField(
            model_name='language',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='language',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Alterado em'),
        ),
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Data de nascimento'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfis',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('comment', models.CharField(max_length=100, verbose_name='Comentario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile', verbose_name='Usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='catalog',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, to='core.Comment', verbose_name='Comentarios'),
        ),
    ]
