# Generated by Django 3.2 on 2022-04-28 01:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220427_2159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='catalog',
            options={'verbose_name': 'Catalogo', 'verbose_name_plural': 'Catalogos'},
        ),
        migrations.AlterModelOptions(
            name='catalogitem',
            options={'verbose_name': 'Iten Catalogo', 'verbose_name_plural': 'Itens Catalogo'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Genero', 'verbose_name_plural': 'Generos'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'Idioma', 'verbose_name_plural': 'idiomas'},
        ),
        migrations.AlterField(
            model_name='catalog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
